const actionTypes = {
  ASYNC_ACTION_PENDING: 'ASYNC_ACTION_PENDING',
  ASYNC_ACTION_ERROR: 'ASYNC_ACTION_ERROR',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  CLOSE_ERROR: 'CLOSE_ERROR',
  GET_ALL_EVENTS: 'GET_ALL_EVENTS',
  GET_EVENT: 'GET_EVENT',
  GET_USER_CREATED_EVENTS: 'GET_USER_CREATED_EVENTS',
  DELETE_EVENT: 'DELETE_EVENT',
  POST_EVENT: 'POST_EVENT',
  GET_USER: 'GET_USER',
  POST_USER: 'POST_USER'
};

export default actionTypes;
