const actionTypes = {
  ASYNC_ACTION_PENDING: 'ASYNC_ACTION_PENDING',
  ASYNC_ACTION_ERROR: 'ASYNC_ACTION_ERROR',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  CLOSE_ERROR: 'CLOSE_ERROR',
  GET_ALL_EVENTS: 'GET_ALL_EVENTS',
  GET_EVENT: 'GET_EVENT',
  GET_USER_CREATED_EVENTS: 'GET_USER_CREATED_EVENTS',
  DELETE_EVENT: 'DELETE_EVENT',
  POST_EVENT: 'POST_EVENT',
  POST_USER: 'POST_USER',
  GET_USER: 'GET_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT: 'LOGOUT',
  ADD_EVENT_TO_GOING: 'ADD_EVENT_TO_GOING',
  REMOVE_EVENT_FROM_GOING: 'REMOVE_EVENT_FROM_GOING',
  GET_ALL_PARTICIPANTS: 'GET_ALL_PARTICIPANTS'
};

export default actionTypes;
