const actionTypes = {
  ASYNC_ACTION_PENDING: 'ASYNC_ACTION_PENDING',
  ASYNC_ACTION_ERROR: 'ASYNC_ACTION_ERROR',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  CLOSE_ERROR: 'CLOSE_ERROR',
  GET_ALL_EVENTS: 'GET_ALL_EVENTS',
  GET_EVENT: 'GET_EVENT'
};

export default actionTypes;
