export const LOAD_USERS_PENDING = 'LOAD_USERS_PENDING';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR';
export const CHANGE_PAGE = 'CHANGE_PAGE';
